name: zasconta_graphql
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  graphql_flutter: ^5.1.2
  # add injectable to your dependencies  
  injectable:
  # add get_it  
  get_it:
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.1
  flutter_bloc: ^8.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  # add the generator to your dev_dependencies  
  injectable_generator:
  # add build runner if not already added  
  build_runner:
  freezed: ^2.3.4
  json_serializable: ^6.7.0

flutter:
  uses-material-design: true
